paths:
  BUCKET_NAME: "s3a://vproptimiserplatform"
  RAW: "raw"
  ORDERS: "orders"
  BRONZE: "bronze"
  SILVER: "silver"
  GOLD: "gold"

raw_data:
  ADDRESS_DATA: "address_data.json"
  CLIENTS_DATA: "client_data.json"
  PRODUCTS_DATA: "full_product_extraction_sample.json"

table_names:
  ADDRESS_TABLE: "address_table"
  CLIENTS_TABLE: "clients_table"
  CLIENTS_ADDRESS_TABLE: "clients_address_table"
  PRODUCTS_TABLE: "products_table"
  PACKAGE_TABLE: "package_table"

raw_paths:
  RAW_ADDRESS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.RAW }}/{{ address_data.ADDRESS_DATA }}"
  RAW_CIENTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.RAW }}/{{ address_data.CLIENTS_DATA }}"
  RAW_PRODUCTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.RAW }}/{{ address_data.PRODUCTS_DATA }}"

bronze_paths:
  BRONZE_ADDRESS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.BRONZE }}/{{ tables.ADDRESS_TABLE }}"
  BRONZE_CLIENTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.BRONZE }}/{{ tables.CLIENTS_TABLE }}"
  BRONZE_PRODUCTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.BRONZE }}/{{ tables.PRODUCTS_TABLE }}"

silver_paths:
  SILVER_ADDRESS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.SILVER }}/{{ tables.ADDRESS_TABLE }}"
  SILVER_CLIENTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.SILVER }}/{{ tables.CLIENTS_TABLE }}"
  SILVER_PRODUCTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.SILVER }}/{{ tables.PRODUCTS_TABLE }}"

gold_paths:
  GOLD_CLIENTS_ADDRESS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.GOLD }}/{{ tables.CLIENTS_ADDRESS_TABLE }}"
  GOLD_PRODUCTS_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ paths.GOLD }}/{{ tables.PRODUCTS_TABLE }}"
  GOLD_PACKAGE_PATH: "{{ paths.BUCKET_NAME }}/{{ paths.ORDERS }}/{{ tables.PACKAGE_TABLE }}"